### ISSUE TITLE
No data receiving on Raspberry Pi 3

### ISSUE THREAD

**Issue by Almer** [bencevans/ve.direct#1]
The VE. Direct naar USB-interface is mounted on /dev/ttyUSB0 and when I do: cat /dev/ttyUSB0 i'm receiving the correct data block every second in my console.

When I run node example.js the console stays empty. Serial port version is 9.0.0

node version: v12.18.3

**Comment by bencevans** [comment]
🤔 Hmmm, I'll check it out here again and get back to you later on...

**Comment by Almer** [comment]
Great. But maybe it's mee doing something stupid but I don't know what. Thanks.

**Comment by Almer** [comment]
Ah. My bad. I was pretty sure al already configured the serial device right in raspi-config but I did it again and.... it works. Sorry for this one.

**Comment by bencevans** [comment]
Oh fab, you beat me to it. Glad to hear you got it working.
